### ISSUE TITLE
Wrong protocol/host when using trustProxy

### ISSUE THREAD

**Issue by mohd-akram** [therealsamf/fastify-url#29]
It returns `localhost` instead of the actual host. Might want to use the `hostname` property on the request.

**Comment by mohd-akram** [comment]
For the protocol, fastify/fastify#1805 would be helpful.

**Comment by therealsamf** [comment]
Thanks for raising the issue @mohd-akram . I’ll try to reproduce this and implement a fix in the near future, currently a little busy.

**Comment by mohd-akram** [comment]
I use this now:

```javascript
  fastify.decorateRequest(
    "absoluteURL",
    /** @this {import('fastify').FastifyRequest} */ function () {
      return new URL(`${this.protocol}://${this.hostname}${this.url}`);
    }
  );
```
